name: Guilty Gear X Plus (Korean)
sha1: cf019ab02686781ee7736fdc61c11007a841aef2
options:
    # paths
    basename: SLPM_645.25
    target_path: iso/SLPM_645.25
    base_path: ..
    
    asm_path: asm
    src_path: src
    build_path: build
    
    extensions_path: tools/splat_ext
    symbol_addrs_path: config/symbol_addrs.txt
    undefined_funcs_auto_path: config/undefined_funcs_auto.txt
    undefined_syms_auto_path:  config/undefined_syms_auto.txt
    
    # compiler 
    compiler: EEGCC
    platform: ps2

    ld_bss_contains_common: True
    
    string_encoding: EUC-JP
    rodata_string_guesser_level: 2 # improve string detection
    disasm_unknown: True
    named_regs_for_c_funcs: False
    gp_value: 0x5d40f0
    # subalign: 4
    include_macro_inc: no # don't write macro.inc to rodata files
    
    find_file_boundaries: False
    section_order: [".text", ".data", ".rodata", ".lit4", ".sdata", ".sbss", ".bss"]
segments:
    - [0, databin, elf_header]
    - name: main
      type: code
      start: 0x1000
      vram: 0x100000
      bss_size: 0x5B200 # should be 1 byte less?
      subalign: null
      subsegments:
        # .text
        - [0x1000, asm, sdk/crt0]

        - [0x11d8, c, ggxeuc/main]
        - [0x1550, c, ggxeuc/graph]
        - [0x1d90, c, ggxeuc/packet]
        - [0x2618, c, ggxeuc/sprite]
        - [0x63c8, c, ggxeuc/job]
        - [0x6428, c, ggxeuc/text]
        - [0x69b0, c, ggxeuc/meter]
        - [0x6ca8, c, ggxeuc/random]
        - [0x6cd0, c, ggxeuc/pad]
        - [0x7270, c, ggxeuc/sin]
        - [0x7558, c, ggxeuc/file]
        - [0x7f18, c, ggxeuc/opening]
        - [0xa420, c, ggxeuc/title]
        - [0xc120, c, ggxeuc/stgsel]
        - [0xf620, c, ggxeuc/vs]
        - [0x11088, c, ggxeuc/survival]
        - [0x14d30, c, ggxeuc/memacc]
        - [0x162a8, c, ggxeuc/g_strip]
        - [0x183a0, c, ggxeuc/pxf]
        - [0x1afb0, c, ggxeuc/fade]
        - [0x1b270, c, ggxeuc/screen]
        - [0x1c128, c, ggxeuc/gcl]
        - [0x1c6a8, c, ggxeuc/dcfont]
        - [0x1d960, c, ggxeuc/allinit]
        - [0x1df80, c, ggxeuc/game]
        - [0x21720, c, ggxeuc/objwork]
        - [0x22c18, c, ggxeuc/player]
        - [0x25a80, c, ggxeuc/polydraw]
        - [0x261f0, c, ggxeuc/credit]
        - [0x270b0, c, ggxeuc/score]
        - [0x27a30, c, ggxeuc/nameentr]
        - [0x27f18, c, ggxeuc/act]
        - [0x2a5d8, c, ggxeuc/gcalc]
        - [0x2a660, c, ggxeuc/diagram]
        - [0x2acd0, c, ggxeuc/fight]
        - [0x329b8, c, ggxeuc/vsctrl]
        - [0x33c78, c, ggxeuc/g_grasub]
        - [0x33ea0, c, ggxeuc/mainctrl]
        - [0x34348, c, ggxeuc/bg]
        - [0x367a0, c, ggxeuc/bgsub]
        - [0x38638, c, ggxeuc/effect]
        - [0x38ce0, c, ggxeuc/replay]
        - [0x3bc48, c, ggxeuc/profile]
        - [0x3cd78, c, ggxeuc/actchk]
        - [0x3eca0, c, ggxeuc/actsub]
        - [0x41468, c, ggxeuc/actsub2]
        - [0x41c08, c, ggxeuc/guardp]
        - [0x42470, c, ggxeuc/playdat]
        - [0x42a28, c, ggxeuc/key]
        - [0x44ad0, c, ggxeuc/cpu]
        - [0x473c0, c, ggxeuc/tension]
        - [0x483c8, c, ggxeuc/colli]
        - [0x4a480, c, ggxeuc/throw]
        - [0x4cae8, c, ggxeuc/plcolchk]
        - [0x4f7b8, c, ggxeuc/object]
        - [0x506e8, c, ggxeuc/cmn_act]
        - [0x534b0, c, ggxeuc/eff_act]
        - [0x54f18, c, ggxeuc/poly_eff]
        - [0x597d0, c, ggxeuc/cockpit]
        - [0x5b4f8, c, ggxeuc/g_grasys]
        - [0x5bd28, c, ggxeuc/g_graph]
        - [0x5d8a8, c, ggxeuc/afterimg]
        - [0x5db90, c, ggxeuc/chase]
        - [0x5e8a8, c, ggxeuc/sobj_act]
        - [0x61ab0, c, ggxeuc/training]
        - [0x65420, c, ggxeuc/opt_main]
        - [0x65ed8, c, ggxeuc/opt_cfg]
        - [0x67490, c, ggxeuc/opt_ajst]
        - [0x679e8, c, ggxeuc/opt_rec]
        - [0x68660, c, ggxeuc/opt_vm]
        - [0x69920, c, ggxeuc/opt_snd]
        - [0x6b590, c, ggxeuc/opt_pass]
        - [0x6c530, c, ggxeuc/ampack]
        - [0x6c590, c, ggxeuc/winner]
        - [0x70190, c, ggxeuc/ending]
        - [0x710b8, c, ggxeuc/finish]
        - [0x728c8, c, ggxeuc/select]
        - [0x77b00, c, ggxeuc/cp_obj]
        - [0x77e70, c, ggxeuc/cp_act]
        - [0x78278, c, ggxeuc/skillref]
        - [0x79270, c, ggxeuc/an_act]
        - [0x7adb8, c, ggxeuc/ane_act]
        - [0x7b3a8, c, ggxeuc/ax_act]
        - [0x7c930, c, ggxeuc/axe_act]
        - [0x7dd00, c, ggxeuc/bk_act]
        - [0x7f1f0, c, ggxeuc/bke_act]
        - [0x7f5f8, c, ggxeuc/ch_act]
        - [0x820a0, c, ggxeuc/che_act]
        - [0x82888, c, ggxeuc/dz_act]
        - [0x839b0, c, ggxeuc/dze_act]
        - [0x86d38, c, ggxeuc/fa_act]
        - [0x895e8, c, ggxeuc/fae_act]
        - [0x8a5e8, c, ggxeuc/jm_act]
        - [0x8d3c0, c, ggxeuc/jme_act]
        - [0x8e2d8, c, ggxeuc/jy_act]
        - [0x902b8, c, ggxeuc/jye_act]
        - [0x91080, c, ggxeuc/ky_act]
        - [0x92778, c, ggxeuc/kye_act]
        - [0x92e70, c, ggxeuc/ml_act]
        - [0x94390, c, ggxeuc/mle_act]
        - [0x96160, c, ggxeuc/my_act]
        - [0x97e10, c, ggxeuc/mye_act]
        - [0x98d58, c, ggxeuc/po_act]
        - [0x9a410, c, ggxeuc/poe_act]
        - [0x9a7a8, c, ggxeuc/sl_act]
        - [0x9c090, c, ggxeuc/sle_act]
        - [0x9c708, c, ggxeuc/ts_act]
        - [0x9dab0, c, ggxeuc/tse_act]
        - [0x9f810, c, ggxeuc/ve_act]
        - [0xa0de8, c, ggxeuc/vee_act]
        - [0xa2698, c, ggxeuc/zt_act]
        - [0xa3b00, c, ggxeuc/zte_act]
        - [0xa4b00, c, ggxeuc/kr_act]
        - [0xa5cc0, c, ggxeuc/kre_act]
        - [0xa63e8, c, ggxeuc/js_act]
        - [0xa7a68, c, ggxeuc/jse_act]
        - [0xa8240, c, ggxeuc/cmn_se]
        - [0xa8600, c, ggxeuc/sound]
        - [0xa94a8, c, ggxeuc/soundnew]
        - [0xa9dd0, c, ggxeuc/memory]
        - [0xab088, c, ggxeuc/nllib]
        - [0xab3b0, c, ggxeuc/system]
        - [0xab758, c, ggxeuc/vibrate]
        - [0xab7d8, c, ggxeuc/gallery]
        - [0xaf420, c, ggxeuc/boss]
        - [0xafcf0, c, ggxeuc/story]

        - [0xb7ad0, asm, sdk/scelib]

        - [0xd5180, data, data]
        
        # .rodata
        - [0x4ba200, rodata]

        # .lit4
        - [0x4cd100, lit4]

        # .sdata
        - [0x4cd580, sdata, sdata]

    - [0x4ceb6c, databin] # .reginfo
    - [0x4ceb84, databin] # .mdebug
    - [0x7476bc, databin] # .shstrtab
    - [0x747714, databin] # _elfSectionHeaders
    - [0x74791c, databin] # .symtab
    - [0x76489c, databin] # .strtab
    - [0x77B103] 