#ifndef PLAYER_H
#define PLAYER_H

typedef union {
	int l;
	short int w[2];
	char b[4];
	u_int ul;
	u_short uw[2];
	u_char ub[4];
	float f;
} PERSONALWORK;

typedef struct {
	short int Tension;
	unsigned char TensionHissatuAddVal;
	unsigned char BackStepInvalid;
	short unsigned int TensionFlag;
	short int NegativeVal;
	short int TensionMaxTime;
	short unsigned int pactst;
	int homingtime;
	int inertia;
	int offx;
	short int notThrowTime;
	short int GuardPoint;
	short int GuardTime;
	short int DownTimer;
	unsigned char HomingJumpDir;
	unsigned char HitCount;
	unsigned char reqhit;
	unsigned char hitDispTime;
	float hitDispIn;
	unsigned char inertiaflag;
	unsigned char whiteouttime;
	unsigned char MutekiTime;
	unsigned char maintain;
	unsigned char SkyDashCorrect;
	unsigned char inertiatime;
	unsigned char DownBoundDamage;
	short unsigned int TensionPenaltyTime;
	unsigned char TensionMovePenaltyTime;
	char JustGuardTime;
	char JustGuardIgnoreTime;
	char JGWhiteTime;
	void *Enemy;
	unsigned int PunchKey;
	unsigned int KickKey;
	unsigned int SlashKey;
	unsigned int HighSlashKey;
	unsigned int Fuckin;
	unsigned int MemoryKey;
	unsigned int PandK;
	unsigned int SandHS;
	unsigned int PKS;
	unsigned int PKSHS;
	short int lifelength;
	short int lifelengthdamage;
	char JumpCount;
	char SkyDashCount;
	unsigned char JumpFlag;
	char ShakeTime;
	unsigned int chainflag;
	unsigned int rendaflag;
	short int FaintPoint;
	short int FaintTime;
	void *ExCommandFunc;
	unsigned char JumpDir;
	char CPU;
	char sousaitime;
	unsigned char FaintMax;
	PERSONALWORK PersonalWork[4];
	short int SpeedSv;
	short unsigned int DownFlag;
	void *Child;
	void *AtkHitInterrupt;
	void *AtkGuardInterrupt;
	void *DamageInterrupt;
	void *LandInterrupt;
	void *GuardFunc;
	void *PosByEnemyAddr;
	unsigned char OverKillFlag;
	unsigned char ObjFlag;
	unsigned char DustTime;
	unsigned char AfterImageIndex;
	void *KeyHook;
	short int lifelengthdamagelock;
	short int TensionBalance;
	short int TensionSideTime;
	short int TensionNoTouchTime;
	int lastposx;
	short int TensionBarLength;
	unsigned char TShand;
	unsigned char EnemyTouch;
	unsigned char AttackDown;
	unsigned char DefenceDown;
	unsigned char JumpSeal;
	unsigned char ArtsSeal;
	unsigned char Poison;
	unsigned char MistTime;
	short unsigned int DamageTime;
} PLAYER_ENTRY;

#endif // PLAYER_H